AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for EMR Serverless Spark jobs (Calendly Delta pipeline)

Resources:
  CalendlyEmrServerlessJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CalendlyEmrServerlessJobRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: emr-serverless.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CalendlyEmrServerlessJobPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: S3Access
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::calendly-marketing-pipeline-data
              - Sid: S3RW
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - arn:aws:s3:::calendly-marketing-pipeline-data/*
              - Sid: GlueCatalog
                Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:CreateDatabase
                  - glue:GetTable
                  - glue:GetTables
                  - glue:CreateTable
                  - glue:UpdateTable
                  - glue:DeleteTable
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:CreatePartition
                  - glue:BatchCreatePartition
                  - glue:UpdatePartition
                Resource: "*"
              - Sid: Logs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
Outputs:
  RoleArn:
    Value: !GetAtt CalendlyEmrServerlessJobRole.Arn
    Export:
      Name: CalendlyEmrServerlessJobRoleArn
